---
- name: WordPress CSS Font Installer
  hosts: wordpress_servers
  gather_facts: yes
  vars_files:
    - config/vars.yml

  tasks:
  
    - name: Run Preflight Checks
      ansible.builtin.include_tasks: tasks/preflight.yml

    - name: Run Font Conversion
      ansible.builtin.include_tasks: tasks/convert_fonts.yml

    - name: Normalise font folder and file names
      ansible.builtin.include_tasks: tasks/normalise_font_names.yml

    - name: Generate CSS Font Template
      ansible.builtin.include_tasks: tasks/generate_css.yml

    - name: Copy CSS Font Template to Theme
      ansible.builtin.include_tasks: tasks/copy_files.yml